### ISSUE TITLE
ImportError with conda-smithy 2.2.2

### ISSUE THREAD

**Issue by tritemio** [conda-forge/conda-smithy#501]
After upgrading from conda-smithy 2.2.1 to 2.2.2 I get an ImportError (system macOS):

```$ conda smithy rerender
Traceback (most recent call last):
  File "/Users/anto/miniconda3/bin/conda-smithy", line 4, in <module>
    import conda_smithy.cli
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/conda_smithy/cli.py", line 10, in <module>
    from conda_build.metadata import MetaData
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 9, in <module>
    from .conda_interface import iteritems, PY3, text_type
  File "/Users/anto/miniconda3/lib/python3.5/site-packages/conda_build/conda_interface.py", line 17, in <module>
    from conda.install import (delete_trash, is_linked, linked, linked_data, move_to_trash,  # NOQA
ImportError: cannot import name 'move_to_trash'
```

**Comment by jakirkham** [comment]
My suspicion is that something else got upgraded, which is not `conda-smithy`. Are you using `conda` 4.2.*? If not, please switch to that version and retry.

**Comment by tritemio** [comment]
@jakirkham, you are right, conda was update to 4.3. Downgrading to 4.2 fixed the issue, thanks!

**Comment by jakirkham** [comment]
We definitely should try to support 4.3. Will look into that after `conda-build-all` supports 4.3.
