### PR TITLE
BUG: Make sure file_config is actually a dictionary

### PR DESCRIPTION
**Pull request by ericdill**
at this point in the code path, it is likely that conda-forge.yml was already
created in cli:generate_feedstock_content() where it defaults to an empty list.
Iterating over that empty list raises the following stack trace:

Traceback (most recent call last):
  File "/Users/travis/miniconda/bin/conda-smithy", line 9, in <module>
    load_entry_point('conda-smithy==0.10.0', 'console_scripts', 'conda-smithy')()
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 228, in main
    args.subcommand_func(args)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 101, in __call__
    generate_feedstock_content(feedstock_directory, args.recipe_directory, meta)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/cli.py", line 32, in generate_feedstock_content
    configure_feedstock.main(target_directory)
  File "/Users/travis/miniconda/lib/python3.5/site-packages/conda_smithy/configure_feedstock.py", line 323, in main
    for key, value in file_config.items():
AttributeError: 'list' object has no attribute 'items'

### CODE REVIEW

**Comment by jakirkham** [comment]
So, I know the config file is initially set as `[]` though it is filled out and changed to a `dict` before anything else happens normally. My understanding is this is done to sniff out other problems that can be easily caught through these types of exceptions and also stop a bad process from continuing.

While we can check to make sure it is a `dict`, I think we are not just glossing over some underlying issue. I'd really like to know what that underlying issue is, but I think @pelson will have a better sense for it.

**Comment by pelson** [comment]
Thanks for tracking this down @ericdill! 

As you say, on ```conda smithy init``` the ``conda-forge.yml`` is defined as `[]` (at https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/cli.py#L30). I'm pretty sure we can improve that, but I wanted to fix and get a v0.10.2 out of the door with it fixed, so have gone for a similar approach to you. The only difference between this and the PR that I merged (#165) was the avoidance of the extra indentation.

Thanks again @ericdill!

**Comment by ericdill** [comment]
Thanks for fixing this properly.  Was the problem #165 or #166 or maybe both?

**Comment by pelson** [comment]
The fix was the same as yours pretty much in #165. #166 fixed another bug introduced.
