### PR TITLE
Use shell quotes for the current platform on the commit hint after re-rendering

### PR DESCRIPTION
**Pull request by nicoddemus**
As discussed in #407

### CODE REVIEW

**Comment by nicoddemus** [comment]
The Travis failure seems to be the same as in #407:

```
AttributeError: 'module' object has no attribute 'ci_register'
```

File: conda_smithy/cli.py [hunk 1]
```diff
@@ -228,9 +228,11 @@ def __call__(self, args):
                         )
                         print("")
                     else:
+                        quote = "'" if not sys.platform.startswith('win') else '"'
                         print(
                             "You can commit the changes with:\n\n"
-                            "    git commit -m 'MNT: Re-rendered with conda-smithy %s'\n" % __version__
+                            "    git commit -m {q}MNT: Re-rendered with conda-smithy {version}{q}\n"
```
Comment (jakirkham) [inline conda_smithy/cli.py]: Honestly I'd be ok just using `"` if that is better for Windows. Both should work fine on Unix as there is nothing fancy going on in the message.

Comment (jakirkham) [inline conda_smithy/cli.py]: I know this was your contribution originally @minrk . Do you care if we just `"` or was there some special reason for `'` that is not coming to me now?

Comment (minrk) [inline conda_smithy/cli.py]: I only used `'` because the surrounding string is `"`, so I wouldn't have to escape. No deeper reason than that. Switching the inner and outer quotes should work fine, too, or escape the inner quotes.

Comment (nicoddemus) [inline conda_smithy/cli.py]: Thanks @jakirkham and @minrk for the feedback.

Updated.

Comment (jakirkham) [inline conda_smithy/cli.py]: Cool, thanks for confirming.

I couldn't remember if we were concerned about shell substitution at one point or not. Certainly shouldn't be a concern for this string.

**Comment by jakirkham** [comment]
Toggling for CI.

**Comment by jakirkham** [comment]
Thanks @nicoddemus and @minrk .
